"""cascade between customer and contract

Revision ID: 1a1159475a1c
Revises: d9b9cd7d81c4
Create Date: 2025-11-03 15:07:44.996330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1159475a1c'
down_revision: Union[str, None] = 'd9b9cd7d81c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
