"""update some str length

Revision ID: 369b7ca57bc8
Revises: 3f29eb2d81c8
Create Date: 2024-07-09 20:37:04.952399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '369b7ca57bc8'
down_revision: Union[str, None] = '3f29eb2d81c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_table', 'name',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('customer_table', 'email',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('customer_table', 'phone',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('customer_table', 'company_name',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.alter_column('event_table', 'location',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=250),
               existing_nullable=False)
    op.alter_column('event_table', 'notes',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_table', 'notes',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('event_table', 'location',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('customer_table', 'company_name',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('customer_table', 'phone',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('customer_table', 'email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('customer_table', 'name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
