"""Added personal_number to user model

Revision ID: 57b4b860b16f
Revises: 369b7ca57bc8
Create Date: 2024-08-06 14:21:16.082168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b4b860b16f'
down_revision: Union[str, None] = '369b7ca57bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('personal_number', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'personal_number')
    # ### end Alembic commands ###
