"""Ajout de contraintes d'unicité

Revision ID: b03f80288a47
Revises: 57b4b860b16f
Create Date: 2024-08-28 10:56:57.306208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03f80288a47'
down_revision: Union[str, None] = '57b4b860b16f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customer_table', ['email'])
    op.create_unique_constraint(None, 'team_table', ['name'])
    op.create_unique_constraint(None, 'user_table', ['personal_number'])
    op.create_unique_constraint(None, 'user_table', ['email'])
    op.create_unique_constraint(None, 'user_table', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_table', type_='unique')
    op.drop_constraint(None, 'user_table', type_='unique')
    op.drop_constraint(None, 'user_table', type_='unique')
    op.drop_constraint(None, 'team_table', type_='unique')
    op.drop_constraint(None, 'customer_table', type_='unique')
    # ### end Alembic commands ###
