"""add optional to event field

Revision ID: d9b9cd7d81c4
Revises: b03f80288a47
Create Date: 2024-10-24 11:09:59.894049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd9b9cd7d81c4'
down_revision: Union[str, None] = 'b03f80288a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_table', 'notes',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('event_table', 'support_contact_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_table', 'support_contact_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('event_table', 'notes',
               existing_type=mysql.VARCHAR(length=1000),
               nullable=False)
    # ### end Alembic commands ###
